# Disable the newline at the start of the prompt
add_newline = false

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[character]
style_success = "#ff69b4"
symbol = "âœ"
error_symbol = "âœ—"
use_symbol_for_status = true

[directory]
style = "#ba55d3"
truncation_length = 0
truncate_to_repo = false

[dotnet]
symbol = "ğŸ¥… "
style = "green"
heuristic = false

[env_var]
disabled = false

[git_branch]
style = "#dda0dd"
symbol = "â™¥:ï˜"
truncation_length = 4
truncation_symbol = ""

[git_commit]
disabled = false
commit_hash_length = 4

[git_state]
progress_divider = " of "
cherry_pick = "ğŸ’ PICKING"

[git_status]
conflicted = "ğŸ³ "
ahea = "ğŸ ğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·<200d>"
modified = "ğŸ“"
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘ "

[hostname]
ssh_only = false
prefix = "âŸª"
suffix = "âŸ«"
trim_at = ".companyname.com"
disabled = true

[jobs]
symbol = "+ "
threshold = 4

[memory_usage]
show_percentage = true
show_swap = true
threshold = -1
symbol = " "
separator = "/"
style = "bold dimmed green"

[nodejs]
style = "#ffc0cb"

[ruby]
symbol = "îˆ¾ "
style = "#ffc0cb"

[package]
style = "#ffc0cb"
symbol = "ï£– "
